"use client";
import {useState} from "react";
type Row={id:string;name:string;kind:string;principalVersion:number;tutor:number;curriculum:number;tutorVersion:number;curriculumVersion:number;role:string;status:string};
export default function PermissionManagement({users,onChanged}:{users:Row[];onChanged:()=>Promise<void>}){
 const [target,setTarget]=useState(""),[capability,setCapability]=useState<"tutor"|"curriculum">("curriculum"),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const user=users.find(u=>u.id===target),active=user?.[capability]===1;
 async function save(e:React.FormEvent){e.preventDefault();if(!user)return;if(user.kind==="student"&&!confirm("Jadikan "+user.name+" staf? Fitur siswa akan dihentikan; riwayat belajar tetap disimpan."))return;setBusy(true);setError("");setNotice("");try{const r=await fetch('/api/permissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:user.kind==='student'?'makeStaff':'setGrant',targetId:user.id,capability,principalVersion:user.principalVersion,grantVersion:user[capability==='tutor'?'tutorVersion':'curriculumVersion'],reason,...(user.kind==='student'?{}:{active:!active})})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Perubahan belum berhasil.');await onChanged();setReason('');setNotice('Izin tersimpan. Tetapkan penugasan kelas atau course melalui menu terkait.');}catch(e){setError(e instanceof Error?e.message:'Perubahan belum berhasil.');}finally{setBusy(false);}}
 return <form className="access-card" onSubmit={save}><h2>Izin kerja staf</h2><p>Tutor dan Tim Kurikulum memiliki izin terpisah. Staf hanya bekerja; pencabutan seluruh izin tidak menjadikan staf sebagai siswa. Pemberian ulang izin memerlukan penugasan ulang.</p><label>Akun<select required value={target} disabled={busy} onChange={e=>{setTarget(e.target.value);setError('');setNotice('');}}><option value="">Pilih akun</option>{users.filter(u=>u.role!=='owner'&&['student','staff'].includes(u.kind)).map(u=><option key={u.id} value={u.id}>{u.name} · {u.kind==='student'?'Siswa':'Staf'}</option>)}</select></label><label>Izin<select value={capability} disabled={busy} onChange={e=>setCapability(e.target.value as typeof capability)}><option value="curriculum">Tim Kurikulum</option><option value="tutor">Tutor</option></select></label>{user&&<p>{user.kind==='student'?'Akun ini akan dijadikan staf.':active?'Izin ini aktif; tindakan berikut mencabut izin.':'Izin ini belum aktif; tindakan berikut memberikan izin.'}</p>}<label>Alasan<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label>{error&&<p role="alert" className="feedback error">{error}</p>}{notice&&<p role="status" className="feedback success">{notice}</p>}<button className="primary" disabled={busy||!user||!reason.trim()||(!active&&user.status!=='active')}>{busy?'Memproses…':user?.kind==='student'?'Jadikan staf dan beri izin':active?'Cabut izin':'Berikan izin'}</button></form>;
}
